FROM node:16-alpine

RUN apk add --no-cache tini=0.19.0-r0
EXPOSE 3000

COPY --chown=node:node ./frontend /app

USER node
WORKDIR /app

RUN yarn install --ignore-scripts && \
    yarn build && \
    yarn install --production --ignore-scripts && \
    yarn cache clean
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["yarn", "start"]
